version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: interview_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: InterviewSimulator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: interview_rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./server
      dockerfile: API.Dockerfile

    volumes:
      - resume_uploads:/app/Uploads
    container_name: interview_api
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=InterviewSimulator;Username=postgres;Password=${POSTGRES_PASSWORD:-123}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - Gemini__ApiKey=${GEMINI_API_KEY}

  worker:
    build:
      context: ./server
      dockerfile: Worker.Dockerfile
    volumes:
    - resume_uploads:/app/Uploads
    container_name: interview_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      api:
        condition: service_started
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=InterviewSimulator;Username=postgres;Password=${POSTGRES_PASSWORD:-123}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - ApiBaseUrl=http://api:8080

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8080"
    container_name: interview_frontend
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  postgres_data:
  resume_uploads:
